require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CmdlinesController do

  def mock_cmdline(stubs={})
    @mock_cmdline ||= mock_model(Cmdline, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cmdlines as @cmdlines" do
      Cmdline.stub(:all) { [mock_cmdline] }
      get :index
      assigns(:cmdlines).should eq([mock_cmdline])
    end
  end

  describe "GET show" do
    it "assigns the requested cmdline as @cmdline" do
      Cmdline.stub(:find).with("37") { mock_cmdline }
      get :show, :id => "37"
      assigns(:cmdline).should be(mock_cmdline)
    end
  end

  describe "GET new" do
    it "assigns a new cmdline as @cmdline" do
      Cmdline.stub(:new) { mock_cmdline }
      get :new
      assigns(:cmdline).should be(mock_cmdline)
    end
  end

  describe "GET edit" do
    it "assigns the requested cmdline as @cmdline" do
      Cmdline.stub(:find).with("37") { mock_cmdline }
      get :edit, :id => "37"
      assigns(:cmdline).should be(mock_cmdline)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cmdline as @cmdline" do
        Cmdline.stub(:new).with({'these' => 'params'}) { mock_cmdline(:save => true) }
        post :create, :cmdline => {'these' => 'params'}
        assigns(:cmdline).should be(mock_cmdline)
      end

      it "redirects to the created cmdline" do
        Cmdline.stub(:new) { mock_cmdline(:save => true) }
        post :create, :cmdline => {}
        response.should redirect_to(cmdline_url(mock_cmdline))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cmdline as @cmdline" do
        Cmdline.stub(:new).with({'these' => 'params'}) { mock_cmdline(:save => false) }
        post :create, :cmdline => {'these' => 'params'}
        assigns(:cmdline).should be(mock_cmdline)
      end

      it "re-renders the 'new' template" do
        Cmdline.stub(:new) { mock_cmdline(:save => false) }
        post :create, :cmdline => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cmdline" do
        Cmdline.stub(:find).with("37") { mock_cmdline }
        mock_cmdline.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cmdline => {'these' => 'params'}
      end

      it "assigns the requested cmdline as @cmdline" do
        Cmdline.stub(:find) { mock_cmdline(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cmdline).should be(mock_cmdline)
      end

      it "redirects to the cmdline" do
        Cmdline.stub(:find) { mock_cmdline(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cmdline_url(mock_cmdline))
      end
    end

    describe "with invalid params" do
      it "assigns the cmdline as @cmdline" do
        Cmdline.stub(:find) { mock_cmdline(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cmdline).should be(mock_cmdline)
      end

      it "re-renders the 'edit' template" do
        Cmdline.stub(:find) { mock_cmdline(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cmdline" do
      Cmdline.stub(:find).with("37") { mock_cmdline }
      mock_cmdline.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cmdlines list" do
      Cmdline.stub(:find) { mock_cmdline }
      delete :destroy, :id => "1"
      response.should redirect_to(cmdlines_url)
    end
  end

end
