require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ExternalAccountsController do

  def mock_external_account(stubs={})
    @mock_external_account ||= mock_model(ExternalAccount, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all external_accounts as @external_accounts" do
      ExternalAccount.stub(:all) { [mock_external_account] }
      get :index
      assigns(:external_accounts).should eq([mock_external_account])
    end
  end

  describe "GET show" do
    it "assigns the requested external_account as @external_account" do
      ExternalAccount.stub(:find).with("37") { mock_external_account }
      get :show, :id => "37"
      assigns(:external_account).should be(mock_external_account)
    end
  end

  describe "GET new" do
    it "assigns a new external_account as @external_account" do
      ExternalAccount.stub(:new) { mock_external_account }
      get :new
      assigns(:external_account).should be(mock_external_account)
    end
  end

  describe "GET edit" do
    it "assigns the requested external_account as @external_account" do
      ExternalAccount.stub(:find).with("37") { mock_external_account }
      get :edit, :id => "37"
      assigns(:external_account).should be(mock_external_account)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created external_account as @external_account" do
        ExternalAccount.stub(:new).with({'these' => 'params'}) { mock_external_account(:save => true) }
        post :create, :external_account => {'these' => 'params'}
        assigns(:external_account).should be(mock_external_account)
      end

      it "redirects to the created external_account" do
        ExternalAccount.stub(:new) { mock_external_account(:save => true) }
        post :create, :external_account => {}
        response.should redirect_to(external_account_url(mock_external_account))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved external_account as @external_account" do
        ExternalAccount.stub(:new).with({'these' => 'params'}) { mock_external_account(:save => false) }
        post :create, :external_account => {'these' => 'params'}
        assigns(:external_account).should be(mock_external_account)
      end

      it "re-renders the 'new' template" do
        ExternalAccount.stub(:new) { mock_external_account(:save => false) }
        post :create, :external_account => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested external_account" do
        ExternalAccount.stub(:find).with("37") { mock_external_account }
        mock_external_account.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :external_account => {'these' => 'params'}
      end

      it "assigns the requested external_account as @external_account" do
        ExternalAccount.stub(:find) { mock_external_account(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:external_account).should be(mock_external_account)
      end

      it "redirects to the external_account" do
        ExternalAccount.stub(:find) { mock_external_account(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(external_account_url(mock_external_account))
      end
    end

    describe "with invalid params" do
      it "assigns the external_account as @external_account" do
        ExternalAccount.stub(:find) { mock_external_account(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:external_account).should be(mock_external_account)
      end

      it "re-renders the 'edit' template" do
        ExternalAccount.stub(:find) { mock_external_account(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested external_account" do
      ExternalAccount.stub(:find).with("37") { mock_external_account }
      mock_external_account.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the external_accounts list" do
      ExternalAccount.stub(:find) { mock_external_account }
      delete :destroy, :id => "1"
      response.should redirect_to(external_accounts_url)
    end
  end

end
