require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe IpfixesController do

  def mock_ipfix(stubs={})
    @mock_ipfix ||= mock_model(Ipfix, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all ipfixes as @ipfixes" do
      Ipfix.stub(:all) { [mock_ipfix] }
      get :index
      assigns(:ipfixes).should eq([mock_ipfix])
    end
  end

  describe "GET show" do
    it "assigns the requested ipfix as @ipfix" do
      Ipfix.stub(:find).with("37") { mock_ipfix }
      get :show, :id => "37"
      assigns(:ipfix).should be(mock_ipfix)
    end
  end

  describe "GET new" do
    it "assigns a new ipfix as @ipfix" do
      Ipfix.stub(:new) { mock_ipfix }
      get :new
      assigns(:ipfix).should be(mock_ipfix)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipfix as @ipfix" do
      Ipfix.stub(:find).with("37") { mock_ipfix }
      get :edit, :id => "37"
      assigns(:ipfix).should be(mock_ipfix)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created ipfix as @ipfix" do
        Ipfix.stub(:new).with({'these' => 'params'}) { mock_ipfix(:save => true) }
        post :create, :ipfix => {'these' => 'params'}
        assigns(:ipfix).should be(mock_ipfix)
      end

      it "redirects to the created ipfix" do
        Ipfix.stub(:new) { mock_ipfix(:save => true) }
        post :create, :ipfix => {}
        response.should redirect_to(ipfix_url(mock_ipfix))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipfix as @ipfix" do
        Ipfix.stub(:new).with({'these' => 'params'}) { mock_ipfix(:save => false) }
        post :create, :ipfix => {'these' => 'params'}
        assigns(:ipfix).should be(mock_ipfix)
      end

      it "re-renders the 'new' template" do
        Ipfix.stub(:new) { mock_ipfix(:save => false) }
        post :create, :ipfix => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipfix" do
        Ipfix.stub(:find).with("37") { mock_ipfix }
        mock_ipfix.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :ipfix => {'these' => 'params'}
      end

      it "assigns the requested ipfix as @ipfix" do
        Ipfix.stub(:find) { mock_ipfix(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:ipfix).should be(mock_ipfix)
      end

      it "redirects to the ipfix" do
        Ipfix.stub(:find) { mock_ipfix(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(ipfix_url(mock_ipfix))
      end
    end

    describe "with invalid params" do
      it "assigns the ipfix as @ipfix" do
        Ipfix.stub(:find) { mock_ipfix(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:ipfix).should be(mock_ipfix)
      end

      it "re-renders the 'edit' template" do
        Ipfix.stub(:find) { mock_ipfix(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipfix" do
      Ipfix.stub(:find).with("37") { mock_ipfix }
      mock_ipfix.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the ipfixes list" do
      Ipfix.stub(:find) { mock_ipfix }
      delete :destroy, :id => "1"
      response.should redirect_to(ipfixes_url)
    end
  end

end
